"""Snippet placeholders, and the espanso match file generated from snippets.toml.

Placeholders in a snippet body:
  {date}             today as 2026-09-24
  {date:%d %B %Y}    any strftime format (also times: {date:%H:%M})
  {clipboard}        the current clipboard text
  {cursor}           where the cursor ends up after pasting (first one only)
Any other text in braces is kept as typed, so code snippets need no escaping.

Pure Python (no GTK) so it can be unit tested.
"""

from __future__ import annotations

import json
import logging
import re
from dataclasses import dataclass
from datetime import datetime
from pathlib import Path

from .config import Snippet

log = logging.getLogger(__name__)

DEFAULT_DATE_FORMAT = "%Y-%m-%d"
_PLACEHOLDER = re.compile(r"\{(?:(date)(?::([^{}\n]*))?|(clipboard)|(cursor))\}")

CURSOR_MARK = "▏"  # where {cursor} is, in the preview
ESPANSO_FILE_NAME = "launcher.yml"
ESPANSO_HEADER = """\
# Generated by the launcher from ~/.config/launcher/snippets.toml. Don't edit this
# file: it is rewritten whenever the snippets change. Use Launcher Settings instead.
"""


@dataclass(frozen=True)
class Part:
    kind: str  # "text", "date", "clipboard" or "cursor"
    value: str = ""  # the text, or the date format


def parse_body(body: str) -> list[Part]:
    parts: list[Part] = []
    pos = 0
    for m in _PLACEHOLDER.finditer(body):
        if m.start() > pos:
            parts.append(Part("text", body[pos : m.start()]))
        if m.group(1):
            parts.append(Part("date", m.group(2) or DEFAULT_DATE_FORMAT))
        elif m.group(3):
            parts.append(Part("clipboard"))
        else:
            parts.append(Part("cursor"))
        pos = m.end()
    if pos < len(body):
        parts.append(Part("text", body[pos:]))
    return parts


def uses_clipboard(body: str) -> bool:
    return any(p.kind == "clipboard" for p in parse_body(body))


def expand(body: str, now: datetime | None = None, clipboard: str = "") -> tuple[str, int]:
    """The text to paste, and how many characters come after {cursor} (0 if none)."""
    now = now or datetime.now()
    before: list[str] = []
    after: list[str] | None = None  # set once the cursor position has been seen
    for part in parse_body(body):
        if part.kind == "cursor":
            if after is None:
                after = []
            continue
        if part.kind == "text":
            text = part.value
        elif part.kind == "date":
            text = _strftime(now, part.value)
        else:
            text = clipboard
        (before if after is None else after).append(text)
    tail = "".join(after or [])
    return "".join(before) + tail, len(tail)


def _strftime(now: datetime, fmt: str) -> str:
    try:
        return now.strftime(fmt)
    except ValueError:
        return fmt


def preview_text(body: str) -> str:
    """The body as shown in the launcher's preview pane (placeholders explained)."""
    out = []
    for part in parse_body(body):
        if part.kind == "text":
            out.append(part.value)
        elif part.kind == "date":
            out.append(_strftime(datetime.now(), part.value))
        elif part.kind == "clipboard":
            out.append("⟨clipboard⟩")
        else:
            out.append(CURSOR_MARK)
    return "".join(out)


# --- espanso -------------------------------------------------------------------------


def espanso_yaml(snippets: tuple[Snippet, ...] | list[Snippet]) -> str | None:
    """espanso matches for the snippets that have a trigger; None if there are none.

    Strings are written as JSON, which is valid YAML, so no YAML library is needed."""
    blocks = []
    for snippet in snippets:
        if not snippet.trigger:
            continue
        text, variables = _espanso_replace(snippet.body)
        lines = [
            f"  - trigger: {json.dumps(snippet.trigger, ensure_ascii=False)}",
            f"    replace: {json.dumps(text, ensure_ascii=False)}",
        ]
        if variables:
            lines.append("    vars:")
            for name, kind, fmt in variables:
                lines += [f"      - name: {name}", f"        type: {kind}"]
                if kind == "date":
                    lines += [
                        "        params:",
                        f"          format: {json.dumps(fmt, ensure_ascii=False)}",
                    ]
        blocks.append("\n".join(lines))
    if not blocks:
        return None
    return ESPANSO_HEADER + "matches:\n" + "\n".join(blocks) + "\n"


def _espanso_replace(body: str) -> tuple[str, list[tuple[str, str, str]]]:
    out: list[str] = []
    variables: list[tuple[str, str, str]] = []  # (name, type, date format)
    cursor = False
    for part in parse_body(body):
        if part.kind == "text":
            out.append(part.value)
        elif part.kind == "cursor":
            if not cursor:
                out.append("$|$")
                cursor = True
        elif part.kind == "clipboard":
            if not any(kind == "clipboard" for _n, kind, _f in variables):
                variables.append(("clipboard", "clipboard", ""))
            out.append("{{clipboard}}")
        else:
            name = next((n for n, k, f in variables if k == "date" and f == part.value), None)
            if name is None:
                name = f"date{sum(k == 'date' for _n, k, _f in variables) + 1}"
                variables.append((name, "date", part.value))
            out.append("{{" + name + "}}")
    return "".join(out), variables


def sync_espanso(snippets: tuple[Snippet, ...], match_dir: Path) -> bool:
    """Write (or remove) espanso's match file for our snippets. Returns True if the file
    changed. Every change makes espanso restart, which briefly steals focus, so the
    file is only touched when its content would actually differ."""
    path = match_dir / ESPANSO_FILE_NAME
    wanted = espanso_yaml(snippets)
    try:
        current = path.read_text(encoding="utf-8")
    except FileNotFoundError:
        current = None
    if wanted == current:
        return False
    if wanted is None:
        path.unlink()
        log.info("removed %s (no snippet has a trigger)", path)
        return True
    if not match_dir.is_dir():
        return False  # espanso isn't set up; nothing to feed
    tmp = path.with_name("." + path.name + ".tmp")  # hidden: espanso ignores it
    tmp.write_text(wanted, encoding="utf-8")
    tmp.replace(path)
    log.info("wrote %d espanso snippets to %s", wanted.count("- trigger:"), path)
    return True
